### ISSUE TITLE
Error received before uploading and after

### ISSUE THREAD

**Issue by ksshehata** [chaddro/EasyPopulate-4.0#16]
MySQLi error 1146: Table 'mrshehata9_zc1.zc_products_with_attributes_stock' doesn't exist
When executing:
SHOW COLUMNS FROM zc_products_with_attributes_stock
using EP4 and open office
also
I downloaded a file made some corrections and tried to uploaded, I got the same error.
Thanks.

**Comment by mc12345678** [comment]
Looks like while the test for the PHP relationship to the database table works successfully, a test to verify that the table exists would be a good next step to this test in case the original SBA files have not been removed.  Fortunately the test function (ep_4_SBA1Exists) is infrequently called so the operations on the database are minimized to once per evolution of the file(s). Perhaps could also set a session variable to minimize the calls if that becomes considered necessary, but then would also at some point need to clean up that session which might require additional code elsewhere which all just seems like too much.. Anyways, leaving myself a note here about the type of check that needs to be incorporated so that this issue can be closed.  Before operating this test, the Table constant should be verified to not only be defined, but also to not be "empty".  Then the following can be tested and if there are results other than 0 or false, then the additional table checks can be performed:
```php
SELECT * 
FROM information_schema.tables
WHERE table_schema = 'yourdb' 
    AND table_name = '<?php echo TABLE_PRODUCTS_WITH_ATTRIBUTES_STOCK; ?>'
LIMIT 1;
```

**Comment by mc12345678** [comment]
Added check for SBA database into admin\functions\extra_functions\easypopulate_4_functions.php as part of the check (Now looks for database file definition as well as database table itself).
