### ISSUE TITLE
Up to date

### ISSUE THREAD

**Issue by reetp** [chaddro/EasyPopulate-4.0#19]
Hi,

I this wondered if you are keeping this up to date. I posted a few patches on the forums which have been incorporated into the fork here 

https://github.com/mc12345678/EasyPopulate-4.0

I note yours is now behind his and just wasn't sure what was the best thing to follow !

B. Rgds
John

**Comment by mc12345678** [comment]
While chadd may or may not respond, he has been busy with other projects for the last two years and recently authorized me to update this repro. I have done that as the version is considered stable as updated on the https://github.com/mc12345678/EasyPopulate-4.0 fork. No report has been made of the changes being considered satisfactory, so this repro hasn't been updated to reflect them.

We had talked about possibly transferring the repro, but thought it would be best overall to maintain the software in the location so many have come to know rather than cause overall confusion.

**Comment by reetp** [comment]
Hi, 

thanks for replying.

So for now it's best to follow yours ? I note you haven't added comments on yours so wasn't sure how to contact you, and hence posting here !

Where is the best place to post issues ? On the forum thread or here ?

B. Rgds
John

**Comment by mc12345678** [comment]
I noticed today that there is no place at the fork of this package to identify issues. Must be a github thing. Generally speaking I would say that issues should be reported on the forum and that items requiring a more "lengthy" approach should be opened here to ensure some form of tracking. As for best to track, well, have been considering beginning a branch off of this repro instead of the separate fork, but either way would be considered something of a beta of the beta. :) on the forum when an update has been made that appears satisfactory for use as self tested,  then it is posted as available. I then try to check back with people to see if they had issues with it (considering many of the changes are to support a specific need they are usually the one(s) to respond indicating satisfactory incorporation/operation). But overall as perhaps seen, I try not to negatively impact operation of the existing software unless it is simply too much to work around and doesn't make sense to keep as is.

I know that there are some things that I was working on to make the software ever more ZC plugin likely such as removing typed/hard-coded text to replace with language constants. (Came across the german version of the software and wanted to incorporate that language information so that it could be easier for them to update and others to provide their language equivalent as seen fit.) These changes if that is all tht would be incorporated would be updated "simultaneously" as they are not so much function related as "display" related.

On that note, and I haven't spoken with chadd about it, but looking at incorporating the possibility of importing by product_id as a switchable option similar to someone identifying to me some form of advanced EZ Populate that was otherwise distributed. Not a 100% fan of the potential issues that could occur, but will have to stand by the remember to backup before use aspect. :/

**Comment by reetp** [comment]
KK, get all that.

If Chadd has let you run this site then it's probably best to focus your attention on this as the main repo and go from there - saves confoosed people like me !

I guess the best idea would probably be to run a dev branch here then (not that I am much good with github myself yet - the little grey cells are too old !)

At least you can keep up with issues/bugs that way which makes sense and is more manageable than a forum thread with x hundred pages which is a nightmare to search through. Forum is OK for a first point of contact and new users who want a bit of help, but you can lose a lot of code in there sometimes !

Yes, a dev branch might be a 'Beta Beta' but you may get some testing from people, and can experiment with stuff without breaking the main branch.

I have to say bulk import is one of the most important aspects of Zen and this is the best bit of code that there is for that. My usage varies depending on sites, but probably will use it more in the forthcoming year so will help where I can.

**Comment by mc12345678** [comment]
Updated master to v4.0.30. Closing this thread.
